int returnDigitNumber(int lengthOfBinary);
void strrev(char* str);
int formateInputWithoutSign(char* str);
char* returnIntPart(char* str);
char* returnFloatPart(char* str);
char* fillBackZeroes(char* str, int bytes);
char* fillLeadingZeroes(char* str, int bytes);
int returnNeededBytes(int numberOfDigits);
char* convertCharToDecimalString(char* str);
void convertAsciiValueToChar(char* str);